config/routes.rb
TheRealAdventureTime::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/featured_pages"

  get "static_pages/about"

  get "static_pages/help"

  resources :groups do
    collection do
      post '/add_user_to_group', :as => :add_user_to_group

    end
    member {put :remove_user_from_group}
  end
  devise_for :users

  resources :users do
    member {post :add_user_to_group }
  end

  resources :pages do
    collection do 
      get 'graph'
    end
    member {post :vote}
  end

  resources :paths
  root :to => 'static_pages#home' 

  match '/graph', :to => 'pages#graph'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def featured_pages
  end

  def about
  end
  
  def help
  
  end
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/featured_pages.html.erb
<h1>Featured Pages</h1>
<%= link_to "The End of Yesterday", Page.find(12), :class => "button keep-white" %><br />
<p>A story of survival in the apocalypse. </p>
<%= link_to "A Day in Middletown", Page.find(1), :class => "button keep-white" %> <br />
<p>You are walking down the street in Middletown. What could possibly go wrong?</p>

app/views/static_pages/help.html.erb
<h1>All around Mandelthought help</h1>

<h3>Nodes</h3>
<p>Mandelthought is a group of branches and nodes. A single node is the starting point for a story. To create a node, visit the <%= link_to "pages", pages_path %> page and click the <%= link_to "new page", new_page_path %> link at the bottom. After that, you can type in your part of the story in the content text area. If you need in page assistance, click the link for help near the top of the page. The title is the name of your page, the stamp text area is an area used for writing a little note to yourself to help you keep track of your pages. You will also see a few radio buttons called groups. It is here that you can chose what group of yours the page belongs to. For most situations, chose the default group. More on groups in a bit </p> 

<br />
<h3>Branches</h3>
<p>To create a branching page, visit the page you want to branch from. After that, click the create branch button at the bottom of the page. All the text areas are the same here, with one exception. You will see a text box entitled "the statement that links this page to the previous page. This is the piece of text that a visitor will see when they visit the node previous page relative to the page you are creating that will allow visitors to visit your page.  </p>
<br />
<h3>Groups</h3>
<p>A group is, in most cases, a collection of like minded individuals that want to share the process of creating pages with one another. All pages are owned by a group. Anyone in the group can edit the pages that belong to the group. To add a user to a group, visit the users profile page and click the add to group button, and then select the group you would like to add them to. To remove a user from a group, go to the edit page for the desired group and click the remove button next to the users name</p>
<br />
<h3>Paths</h3>
<p>Not only can users create pages and branches, but they can also create paths. A path is a page linking one page to another page. To create a path, visit the page that you want the path to link from. Then click the create path button. From there, type in and select the page you want the path to link to, and then provide a statement that will link the pages. </p>

app/views/static_pages/home.html.erb
<h1 class="center"> Welcome to Mandelthought</h1>
<p>This is Mandelthought</p>
<%= link_to "The various pages that form Mandelthought", pages_path, :class => "button small keep-white" %>
<br />
<%= link_to "A graph of the Mandelthought network", graph_pages_path, :class => "button small keep-white" %>
<br />
<%= link_to "Some suggested starting points", static_pages_featured_pages_path, :class => "button small keep-white" %>