config/routes.rb
TheRealAdventureTime::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/featured_pages"

  get "static_pages/about"

  get "static_pages/help"

  resources :groups do
    collection do
      post '/add_user_to_group', :as => :add_user_to_group

    end
    member {put :remove_user_from_group}
  end
  devise_for :users

  resources :users do
    member {post :add_user_to_group }
  end

  resources :pages do
    collection do 
      get 'graph'
    end
    member {post :vote}
  end

  resources :paths
  root :to => 'static_pages#home' 

  match '/graph', :to => 'pages#graph'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :pages

  has_many :memberships
  has_many :users, :through => :memberships

  validates :title, obscenity: true
  validates :description,  obscenity: { sanitize: true, replacement: :default}

  has_reputation :votes, source: {reputation: :votes, of: :pages}, aggregated_by: :sum, source_of: [{:reputation => :votes, :of => :users}]

  def votes
    self.reputation_for(:votes)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_ownership, :only => [:destroy, :update, :edit, :remove_user_from_group]
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @users = User.search(params[:search]).order("name asc").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.users << current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    if !@group.pages.empty? 
      flash[:error] = "You can't destroy this group, it has pages associated with it."
      redirect_to groups_url
    else
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
  end

  def remove_user_from_group 
    @group = Group.find(params[:id])
    @user = User.find(params[:user])
    Membership.find_by_user_id(params[:user]).destroy 
    redirect_to :back
  end

    private
  def check_ownership
    @group = Group.find(params[:id])
    unless current_user.groups.include?(@group) || current_user.admin?
      flash[:error] = "You do not belong to this group"
        redirect_to groups
      end
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_add_user.html.erb
	<ul id="groups" class="f-dropdown">
		<p>
	<% if @user != current_user %>
	<%= form_tag({:controller => "users", :action => "add_user_to_group"}, :method => "post") %>
		<% current_user.groups.each do |group| %>
			<li><%= radio_button_tag(:group, group.id) %></li>
			<li><%= label_tag(group.title) %></li>
		<% end %>
		<%= hidden_field_tag(:user, @user.id) %>
		<li> <%= submit_tag("Submit") %> </li>
	<% end %>
</p>
	</ul>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <p>
  <ul>
  <% @group.users.each do |user| %>
  <li>
    <%= link_to user.name, user %> | <%= link_to "Remove user from group", remove_user_from_group_group_path(@group, :user => user.id), :method => :put, :user => user.id %>
  </li>
  <% end %>
  </ul>
</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/add_user_to_group.html.erb
<% if current_user %>
<%= form_tag(add_user_to_group_path, :method => "post") do %>
  <% current_user.groups.each_with_index do |group, i| %>
        <% if i == 0 %> 
          <%= label_tag group.title %>
          <%= radio_button_tag :group_id, group.id, :default => true %>
          <% else %>
          <%= label_tag group.title %>
          <%= radio_button_tag :group_id, group.id %>
        <% end %>
    <% end %>
<% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.title %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= group.votes %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @group.title %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>
<p>
	<b>Members:</b>
	  <% @group.users.each do |user| %>
  <li>
    <%= link_to user.name, user %> 
  </li>
  <% end %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>