config/routes.rb
TheRealAdventureTime::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/featured_pages"

  get "static_pages/about"

  get "static_pages/help"

  resources :groups do
    collection do
      post '/add_user_to_group', :as => :add_user_to_group

    end
    member {put :remove_user_from_group}
  end
  devise_for :users

  resources :users do
    member {post :add_user_to_group }
  end

  resources :pages do
    collection do 
      get 'graph'
    end
    member {post :vote}
  end

  resources :paths
  root :to => 'static_pages#home' 

  match '/graph', :to => 'pages#graph'

end

app/views/pages/_edit_form.html.erb
<%= tinymce_assets %>
<%= form_for(@page) do |f| %>

<%= render 'form', :f => f %>
<%= f.fields_for :group do |group_builder| %>

  <% current_user.groups.each do |group| %>
  <%= radio_button_tag :group_id, group.id %> <%= group.title %>

<% end %>
<% end %>
  <% if !@page.reverse_pages.empty? %>
    <%= f.fields_for :paths do |path_builder| %>

      <br />
        <%= path_builder.label :question, "The statment that links this page to the previous page: " + path_builder.to_s %>
        <%= path_builder.text_field :question %>
      <% end %>

  <% end %>
  <% if current_user.admin? %>
    <%= f.label :color %>
    <%= f.text_field :color, :class => "color-picker" %>
  <% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/pages/_form.html.erb
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="content-field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => "tinymce", :rows => 200, :cols => 120 %>
    <%= tinymce %>
  </div>
  <div class="field">
    <%= f.label :stamp %><br />
    <%= f.text_field :stamp, :id => "stamp-field"  %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :id => "title-field"  %>
  </div>

app/views/pages/_new_form.html.erb
<%= tinymce_assets %>
<%= form_for(@page) do |f| %>
  <%= render 'form', :f => f %>
  
    <%= f.fields_for :paths do |builder| %>
      <div class="field" id="path-field">
        <%= builder.label :question, "The statment that links this page to the previous page" %><br />
        <%= builder.text_field :question   %>
        <%= builder.hidden_field :page_from_id, :value => @root.id %>
      </div>
    <% end %>
    <div class="field" id="group-field">
    <%= f.fields_for :group do |group_builder| %>

        <% current_user.groups.each_with_index do |group, i| %>
        <% if i == 0 %> 
          <%= label_tag group.title %>
          <%= radio_button_tag :group_id, group.id, :default => true, :id => "group-field" %>
          <% else %>
          <%= label_tag group.title %>
          <%= radio_button_tag :group_id, group.id %>
        <% end %>
        <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/pages/_pages.html.erb
<table>
  <tr>
    <th>Stamp</th>
    <th>Title</th>
    <th>Votes</th>
    <th>Child Pages</th>
    <th>Parent Pages</th>
    <th>Group</th>
    <th></th>
    <% if current_user %>
    <th></th>
    <th></th>
    <% end %>

  </tr>

  <% @pages.each do |page| %>
  <tr>
    <td><%= page.stamp %></td>
    <td><%= page.title %></td>
    <td><%= page.votes.to_s[/[^.]+/] %></td>
    <td>
      <% page.pages.each_with_index do |related_page, i| %>
      <% if i == 0 %>
      |
      <% end %>
      <%= link_to related_page.title, related_page %> |
      <% end %>
    </td>
    <td>
      <% page.reverse_pages.each_with_index do |related_reverse_page, i | %>
      <% if i == 0 %>
      |
      <% end %>
      <%= link_to related_reverse_page.title, related_reverse_page %> | 
      <% end %>
    </td>
    <td><%= page.group.title %></td>
    <td><%= link_to 'Show', page %></td>
    <% if current_user %>
    <% if (page.group.users.include?(current_user)) or current_user.admin %>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <% end %>
    <% end %>

  </tr>
  <% end %>
</table>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/graph.html.erb
<div class="graph">
</div>

app/views/pages/index.html.erb
<h1>Listing pages</h1>
<%= form_tag pages_path, :method => 'get', :id => "pages_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<div id="pages"><%= render 'pages' %></div>
<%= paginate @pages %>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/index.js.erb
$('#pages').html('<%= escape_javascript(render("pages")) %>');

app/views/pages/new.html.erb
<h1>New page</h1>
<a id="help">Need help? Click here!</a>
<%= render 'new_form' %>
<ol data-joyride id="joyride" style="display: none;">

  <li>This is the basic information you will need in order to create your page</li>

  <li data-id="content-field">This is where you type the content of the page. Be lengthy, and be sure to pertain to the plot. Feel free to add pictures. </li>

  <li data-id="stamp-field">Use the stamp field to make notes to help you keep track of your story. This will not be shown to the viewers of the page</li>

  <li data-id="title-field">Name your page here. This will be shown to the reader</li>

  <li data-id="path-field">This is important - use this field to tie this page to the previous page. This will be the option shown to the user that will take them to this page</li>

  <li data-id="group-field">The group that this page belongs to. All users in the group will be able to edit the page </li>

  <li> For more detailed information, visit <%= link_to "Help", static_pages_help_path, :class => "button small" %> </li>

</ol>

<%= link_to 'Back', :back %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">
  <b>  <%= @page.title %></b>

</h1>
<p>
  <% begin %>
  <%= @page.content.bbcode_to_html(:disable => :image).html_safe %>
  <% rescue %>
  <%= @page.content %>
  <% end %>
</p>

<% @page.reverse_paths.each do |path| %>
<%= link_to path.question + ' +' + Page.find(path.page_to_id).reputation_for(:votes).to_s[/[^.]+/], Page.find(path.page_to_id), :class => 'small button keep-white' %>
<br />
<% end %>
<%= link_to "Promote", vote_page_path(@page, type: "up"), method: "post", class: "tiny button success" %> 

<%= link_to "Demote", vote_page_path(@page, type: "down"), method: "post", class: "tiny button alert"%> 

<div class="tiny button secondary" > <%= @page.reputation_for(:votes).to_i %> + </div>

<%= link_to 'Edit', edit_page_path(@page), class: "tiny button secondary"%> 
<%= link_to 'Create Branch', new_page_path(:root_id => @page.id), class: "tiny button secondary"%>
<%= link_to 'Create Path', new_path_path(:root_id => @page.id), class: "tiny button secondary"%>
<%=	render 'layouts/add_this' %>