config/routes.rb
TheRealAdventureTime::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/featured_pages"

  get "static_pages/about"

  get "static_pages/help"

  resources :groups do
    collection do
      post '/add_user_to_group', :as => :add_user_to_group

    end
    member {put :remove_user_from_group}
  end
  devise_for :users

  resources :users do
    member {post :add_user_to_group }
  end

  resources :pages do
    collection do 
      get 'graph'
    end
    member {post :vote}
  end

  resources :paths
  root :to => 'static_pages#home' 

  match '/graph', :to => 'pages#graph'

end

app/views/layouts/_add_this.html.erb
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5174928c555f96d2"></script>
<!-- AddThis Button END -->

app/views/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40127415-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_top_menu.html.erb
<li><%= link_to('Graph', '/graph') %> </li>
<li><%= link_to('Pages', pages_path) %></li>
<li><%= link_to('Users', users_path) %> </li> 
<li><%= link_to('Groups', groups_path) %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Mandelthought" %></title>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "vendor/custom.modernizr" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="fixed">
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Home", root_url %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <%= render 'layouts/top_menu' %>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
    	
    	<%= render 'devise/menu/login_items' %>
    	     <li class="has-dropdown"><a href="#">Me</a>

        <ul class="dropdown">
          <%= render 'devise/menu/registration_items' %>
        </ul>
      </li>
    </ul>

  </section>
</nav>
</div>
	<div class="bgsky">
	</div>
	<div class="row">
		<div class="small-11 small-centered middleofscreen columns panel parchment">
			<% if flash[:error] %>
			<%= content_tag :div, :id => "flash_name", :class => "alert-box alert" do %>
			<%= flash[:error] %>
			<a class="close">x</a>
			<% end %>
			<% end %>

			<% if flash[:notice] %>
			<%= content_tag :div, :id => "flash_name", :class => "alert-box success" do %>
			<%= flash[:notice] %>
			<a class="close">x</a>
			<% end %>
			<% end %>

			<%= yield %>
		</div>
	</div>

	<%= javascript_include_tag "application" %>
	<%= render :partial => 'layouts/ga' if Rails.env.production? %>

		 <script type="text/javascript">
		 $("#help").click(function(){
  			$(document).foundation('joyride', 'start');
		 });

</script>
</body>

</html>